# Generated by Django 3.2.9 on 2023-04-10 17:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.png', upload_to='images')),
                ('desc', models.TextField(default='description')),
                ('headerText1', models.CharField(default='Hi there!,\n I am Nilesh', max_length=100)),
                ('headerText2', models.CharField(default='Welcomes to my blogpost', max_length=100)),
                ('headerImage', models.ImageField(default='boat.png', upload_to='images')),
                ('githubLink', models.CharField(default='google.com', max_length=200)),
                ('instagramLink', models.CharField(default='google.com', max_length=200)),
                ('linkedInLink', models.CharField(default='google.com', max_length=200)),
                ('footerHeader', models.CharField(default='Nilesh Chandrakant', max_length=200)),
                ('footerSubheader', models.CharField(default='I can do anything, nothing is impossible and thats it', max_length=300)),
                ('phoneNumber', models.CharField(default='', max_length=13)),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.png', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.png', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default.png', upload_to='images')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.TextField(default='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
            ],
        ),
    ]
