# Generated by Django 3.2.9 on 2023-02-05 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='desc',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
