# Generated by Django 3.2.9 on 2023-03-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_aboutme_imagegallery_recentwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='headerImage',
            field=models.ImageField(default='boat.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='headerText1',
            field=models.CharField(default='Hi there!,\n I am Nilesh', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='headerText2',
            field=models.CharField(default='Welcomes to my blogpost', max_length=100),
        ),
    ]
