# Generated by Django 3.2.9 on 2023-03-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20230325_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='footerHeader',
            field=models.CharField(default='Nilesh Chandrakant', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='footerSubheader',
            field=models.CharField(default='I can do anything, nothing is impossible and thats it', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='githubLink',
            field=models.CharField(default='google.com', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='instagramLink',
            field=models.CharField(default='google.com', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='linkedInLink',
            field=models.CharField(default='google.com', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='phoneNumber',
            field=models.CharField(default='', max_length=13),
        ),
    ]
